### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by jiwonpark1994** [SES-5215-F2020/jiwonpark-quant#1]
Both the Rmd file and html file (title : Assignment-1.html) are ready for grading. I got the idea about how to approach my question by looking at Cat's example assignment. It really helped me a lot, so thank you!

I hope you enjoy it and look forward to getting your feedback!

**Comment by saratepfer** [comment]
Thank you, Jiwon! nice job. Your number of observations, unit of analysis, and population are all clearly stated. Your code is clear. You are currently working with a lot of variables, so it's possible to eliminate some over the course of the semester. You may also have to slightly re-think the majority transportation variable, in case no one form of transportation is > 0.5 for a given tract.

**Comments on code**
Line 87: I would add a line here that indicates TRUE ~ "No Majority", which I think should resolve many of the NAs we see in the maj_edu variable.
